# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-24 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0003_auto_20210820_1713'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20210811_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('count', models.IntegerField(default=1, verbose_name='\u6570\u91cf')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u5355\u4ef7')),
                ('comment', models.TextField(default='', verbose_name='\u8bc4\u4ef7\u4fe1\u606f')),
                ('score', models.SmallIntegerField(choices=[(0, '0\u5206'), (1, '20\u5206'), (2, '40\u5206'), (3, '60\u5206'), (4, '80\u5206'), (5, '100\u5206')], default=5, verbose_name='\u6ee1\u610f\u5ea6\u8bc4\u5206')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='\u662f\u5426\u533f\u540d\u8bc4\u4ef7')),
                ('is_commented', models.BooleanField(default=False, verbose_name='\u662f\u5426\u8bc4\u4ef7\u4e86')),
            ],
            options={
                'db_table': 'tb_order_goods',
                'verbose_name': '\u8ba2\u5355\u5546\u54c1',
                'verbose_name_plural': '\u8ba2\u5355\u5546\u54c1',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('order_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='\u8ba2\u5355\u53f7')),
                ('total_count', models.IntegerField(default=1, verbose_name='\u5546\u54c1\u603b\u6570')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u5546\u54c1\u603b\u91d1\u989d')),
                ('freight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u8fd0\u8d39')),
                ('pay_method', models.SmallIntegerField(choices=[(1, '\u8d27\u5230\u4ed8\u6b3e'), (2, '\u652f\u4ed8\u5b9d')], default=1, verbose_name='\u652f\u4ed8\u65b9\u5f0f')),
                ('status', models.SmallIntegerField(choices=[(1, '\u5f85\u652f\u4ed8'), (2, '\u5f85\u53d1\u8d27'), (3, '\u5f85\u6536\u8d27'), (4, '\u5f85\u8bc4\u4ef7'), (5, '\u5df2\u5b8c\u6210'), (6, '\u5df2\u53d6\u6d88')], default=1, verbose_name='\u8ba2\u5355\u72b6\u6001')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Address', verbose_name='\u6536\u8d27\u5730\u5740')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='\u4e0b\u5355\u7528\u6237')),
            ],
            options={
                'db_table': 'tb_order_info',
                'verbose_name': '\u8ba2\u5355\u57fa\u672c\u4fe1\u606f',
                'verbose_name_plural': '\u8ba2\u5355\u57fa\u672c\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='orders.OrderInfo', verbose_name='\u8ba2\u5355'),
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.SKU', verbose_name='\u8ba2\u5355\u5546\u54c1'),
        ),
    ]
