# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-08 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_active',
            field=models.BooleanField(default=False, verbose_name='\u90ae\u7bb1\u9a8c\u8bc1\u72b6\u6001'),
        ),
    ]
