# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-11 14:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('users', '0002_user_email_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('title', models.CharField(max_length=20, verbose_name='\u5730\u5740\u540d\u79f0')),
                ('receiver', models.CharField(max_length=20, verbose_name='\u6536\u8d27\u4eba')),
                ('place', models.CharField(max_length=50, verbose_name='\u5730\u5740')),
                ('mobile', models.CharField(max_length=11, verbose_name='\u624b\u673a')),
                ('tel', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='\u56fa\u5b9a\u7535\u8bdd')),
                ('email', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='\u7535\u5b50\u90ae\u7bb1')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='\u903b\u8f91\u5220\u9664')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_addresses', to='areas.Area', verbose_name='\u5e02')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='district_addresses', to='areas.Area', verbose_name='\u533a')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='province_addresses', to='areas.Area', verbose_name='\u7701')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'ordering': ['-update_time'],
                'db_table': 'tb_address',
                'verbose_name': '\u7528\u6237\u5730\u5740',
                'verbose_name_plural': '\u7528\u6237\u5730\u5740',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='default_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.Address', verbose_name='\u9ed8\u8ba4\u5730\u5740'),
        ),
    ]
