# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-10 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u540d\u79f0')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='areas.Area', verbose_name='\u4e0a\u7ea7\u884c\u653f\u533a\u5212')),
            ],
            options={
                'db_table': 'tb_areas',
                'verbose_name': '\u7701\u5e02\u533a',
                'verbose_name_plural': '\u7701\u5e02\u533a',
            },
        ),
    ]
