# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-14 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('url', models.CharField(max_length=300, verbose_name='\u5185\u5bb9\u94fe\u63a5')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='\u56fe\u7247')),
                ('text', models.TextField(blank=True, null=True, verbose_name='\u5185\u5bb9')),
                ('sequence', models.IntegerField(verbose_name='\u6392\u5e8f')),
                ('status', models.BooleanField(default=True, verbose_name='\u662f\u5426\u5c55\u793a')),
            ],
            options={
                'db_table': 'tb_content',
                'verbose_name': '\u5e7f\u544a\u5185\u5bb9',
                'verbose_name_plural': '\u5e7f\u544a\u5185\u5bb9',
            },
        ),
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('key', models.CharField(max_length=50, verbose_name='\u7c7b\u522b\u952e\u540d')),
            ],
            options={
                'db_table': 'tb_content_category',
                'verbose_name': '\u5e7f\u544a\u5185\u5bb9\u7c7b\u522b',
                'verbose_name_plural': '\u5e7f\u544a\u5185\u5bb9\u7c7b\u522b',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contents.ContentCategory', verbose_name='\u7c7b\u522b'),
        ),
    ]
