# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-20 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsVisitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name=b'\xe6\x9b\xb4\xe6\x96\xb0\xe6\x97\xb6\xe9\x97\xb4')),
                ('count', models.IntegerField(default=0, verbose_name='\u8bbf\u95ee\u91cf')),
                ('date', models.DateField(auto_now_add=True, verbose_name='\u7edf\u8ba1\u65e5\u671f')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='\u5546\u54c1\u5206\u7c7b')),
            ],
            options={
                'db_table': 'tb_goods_visit',
                'verbose_name': '\u7edf\u8ba1\u5206\u7c7b\u5546\u54c1\u8bbf\u95ee\u91cf',
                'verbose_name_plural': '\u7edf\u8ba1\u5206\u7c7b\u5546\u54c1\u8bbf\u95ee\u91cf',
            },
        ),
        migrations.AlterField(
            model_name='sku',
            name='default_image_url',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to=b'', verbose_name='\u9ed8\u8ba4\u56fe\u7247'),
        ),
    ]
