# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-20 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20210820_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='default_image_url',
            new_name='default_image',
        ),
    ]
